---
title: "Co-ocurrence"
author: "Orlando Camargo"
date: '2022-07-01'
output: html_document
---

## Co-ocurrence analysis

Set working directory and load libraries
```{r}
setwd("/home/orlando/data/pocean_metagenome/")
#BiocManager::install("rhdf5")
#BiocManager::install("phyloseq")
library("phyloseq")
library("ggplot2")
library("readr")
library("patchwork")
```

## Import BIOM file

```{r}
merged_metagenome_op<- import_biom("pacific_ocean.biom")
mydata<-merged_metagenome_op@otu_table
mydata<-as.data.frame(mydata)
head(mydata)
data<-mydata
rownames(data)<-1:nrow(data)
head(data)
```

## Presence and absence of species

```{r}
data$first<-rep(1, each=nrow(data))
data<- data[ , c("first",names(data)[names(data) != "first"])]

data$last<-rep(1, each=nrow(data))

y=as.single(c())
df_n<-data.frame(row.names = rownames(data))
for (i in colnames(data)){
  print(paste("running:",i,"..."))
  df_n[,i]<-y
  for(z in rownames(df_n)){
    if(data[z,i]>=5){ #este número es arbitrario podemos usar porcentajes de abudancia
      y[z]=1
    }else{
      y[z]=0
    }
  }
}

df_n<-df_n[,-c(1:2)]
colnames(df_n)<-colnames(mydata)

head(df_n)
```

## Co-ocurrence analysis by C-score and Spearman correlation

Permutation of 10 OTU's like test
```{r}
#install.packages("combinat")
library("combinat")
#sam<-sample(1:400, 10, replace = TRUE )
df_n1<-df_n[c(716:726),]
#df_n1<-df_n
comn<- as.data.frame(combn(1:nrow(df_n1), 2))
data1<-mydata
rownames(data1)<-1:nrow(data1)
head(data1)
```

Selection of OTUs by C-score and Spearman correlation

```{r}
list_oc <-list()
for (i in colnames(comn)){
  print(comn[,i])
  perm=comn[,i]
  ocdf=df_n1[c(min(perm), max(perm)),]
  names=rownames(data1[c(min(perm), max(perm)),])
  cij<-(length(ocdf[1,])-sum(ocdf[1,]))*(length(ocdf[2,])-sum(ocdf[2,]))
  spearm=data1[c(min(perm),max(perm)),]
  cort<-cor.test(as.numeric(spearm[1,]),as.numeric(spearm[2,]), method = "spearman", conf.level = 0.95, exact=FALSE)
  if (cij>0 & cort$p.value<1){
    list_oc[[i]]<-c(names,ocdf,cij,cort$p.value)
  }else{
    print(paste("drop..."))
  }
}

head(list_oc,1)
```


